language: node_js
node_js:
  - "5"
before_script:
  - npm install -g grunt
  - npm i
  - ./node_modules/protractor/bin/webdriver-manager update
  # - ./node_modules/protractor/bin/webdriver-manager start
script: grunt e2e-travis
