language: node_js
node_js:
  - "5"
before_script:
  - npm install -g grunt
  - npm i
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - ./node_modules/protractor/bin/webdriver-manager update --standalone --firefox
  - ./node_modules/protractor/bin/webdriver-manager start 2>&1 &
  - sleep 3
script: 
  - grunt e2e-exec
  - grunt e2e-travis

