language: node_js
node_js:
  - "0.12"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - ./node_modules/protractor/bin/webdriver-manager update --standalone --firefox
  - ./node_modules/protractor/bin/webdriver-manager start 2>&1 &  
  - sleep 3

  # - wget http://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar
  # - java -jar selenium-server-standalone-2.52.0.jar > /dev/null &
  # 
  # - ./node_modules/protractor/bin/webdriver-manager start
script: grunt e2e-travis

