language: node_js
node_js:
- '5'
before_install:
- gem update --system
- gem install compass
before_script:
- npm install -g grunt
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- ./node_modules/protractor/bin/webdriver-manager update --standalone --firefox
- ./node_modules/protractor/bin/webdriver-manager start 2>&1 &
- sleep 3
script:
- grunt unit-travis
- grunt build
- grunt e2e-travis
- if [ "$TRAVIS_BRANCH" == "master" ]; then grunt ftp_push --ftpUser=$USERNAME --ftpPass=$PASSWORD; fi
env:
  global:
  - secure: HwPl6j6fu69KRN2rUtBEYURBM8eRJxynHpN5U/RkJxtT0z3EFal09vHOPiE9yN5TEMilSvECvZRn7aJr2xZnYr+FY/HdeOoepAeBe97hv9aW3JVrAWcmZdLFOnb5aHdNkwSgOd6E9fpXfe5O3EzwsjunriPg8FH3ZGmBKA5rRh/w5ufd1UbPj+WKpkzDNXvZmUuU1espEOOZJP+MxE/qCnkp3Km9GUzRAjHd28HefzFCVM/9aMutljpuUrdU/wRDZ+lFmi/6wtORmnk0012eSgxTWMVxk0t1TKpd2m3qqWoiBKX/thS+dz7qCZ8o/+DEbCtZJaQtYBY9/bd6AqQlu05AnXq8pegGfTaDRWUp5zOO3J8Ugu5k6Nbz6MxkZKuqe2EbD3y4IXys4LSWzSxf4SpN6ZjbAkDpiFWssHvxwgBEbQDFZOslY1B+lG0JUs+IXgtZYQHn7pMyS5QqSGkkm8kjTKktdjT/jadLz5ms5igBeMzcs9tiHGS744ZoBEuBV8Z41nyFapOp0f//2hqEBWAhKjOWOJtcKYdxwzRIejh15B3/rET812VhOhPI7gA5lDjrnaBAIXwKapIW1OEXfg39fn6yOOuC++fCpHXbQg2lGZWvO6BiA9DO2IFXn8OHF5GyVKZrVGzx7pQC174saHcnSwNhssABKN/agwfBQVQ=
  - secure: VKMRvRIwu59w0kBQqPbJGUu3+UvW96YBLeVkhVDgLTjwI34FP+tPqSOH18i3/Q1Uhb1jwB3NhPbwZWmziJT4NLBhU5gVRWL+vphtsK+iObB8g2e1onVsm949ZnDB0i4MNowJgSJFOh91goq1oifUBCeX7XMmdhTbVqIQ45JPHbYEXlIzUHB1A2uJv3FzdtUBEkPZINeTDHkuiTcAR26gzbKVB601VmoGZ6e9hqGnTsPyEhExpIf7zDd1x3/waNxfcSn2sTyNq7kZjNTlRkf/L3phu12ZRo09Z+FkuH1SiKFjIlcoWNhXq/uE1i4PPzlISVlcesV3hVRYaaGYBVcQF8bggK4xc96HdTfEvG2XbBkNgo10TBckA8lQeRoa8XJ2gJvcKqXJxfGRdXudASxbjhZ0BC6FhuD6ZySI8zHICEQC146mVSWhUD8gJvhCrNr4YmFARDU/1TD6z71jxOjVPKWE7TuynAKTHJe86PfjGPLpa5bqh4lHb0AWh6k45V8A5mckhYPC6mZPQg5FVCA3YsSt6uK/+zrjc+JdOQlNUo80M1OKsmX46ilUM31OCnFenl09pvXORqDi2v6h8TacXTZ+Fk5qG8zu3sTwHmoxErbrDCnT16N9a0W5BsKLtGm6uFvSBJ1+RWDfwDhhSuVAwTypZ8wUIbroQjiwe4pi6+4=
after_success:
  - cat coverage/*/lcov.info | ./node_modules/codecov.io/

